Parameters:
  InstanceType:
    Description: WebServer EC2 instance type (has default, AllowedValues)
    Type: String
    Default: t2.small
    AllowedValues:
        - t1.micro
        - t2.nano
        - t2.large
        - t2.small
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: give the Keyname
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: add the Keypair name

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      #we reference the InstanceType parameter
       InstanceType: !Ref InstanceType
       KeyName: !Ref KeyName
       ImageId: "ami-a4c7edb2"